package amongthem.rooms;

public enum RoomNames {
    UPPER_ENGINE, REACTOR, SECURITY, MEDBAY, LOWER_ENGINE, ELECTRICAL, STORAGE, COMMUNICATION, SHIELDS, ADMIN, NAVIGATION, O2, WEAPONS, CAFETERIA,
    CAFETERIA_WEAPONS_PATH, WEAPONS_O2_NAVIGATION_SHIELDS_PATH, SHIELDS_COMMUNICATION_STORAGE_PATH, CAFETERIA_ADMIN_STORAGE_PATH,
    CAFETERIA_MEDBAY_UPPER_ENGINE_PATH, UPPER_ENGINE_SECURITY_REACTOR_LOWER_ENGINE_PATH, LOWER_ENGINE_ELECTRICAL_STORAGE_PATH
}
